import type { ReactNode } from 'react';
import React from 'react';
import "../globals.css";
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};


export default function layout ({children}: { children:ReactNode }):ReactNode {
    return <body>
        {children}
    </body>
};