import type { Metadata } from "next";
import { Sidebar } from "../../components/sidebar/index";
import {Roboto} from "next/font/google";
import "../globals.css";
import { Toaster } from "sonner";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets:["latin"]
})


export const metadata: Metadata = {
  title: "Taks Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}  antialiased`}
      >
        <Toaster/>
        <div className="grid grid-cols-12 w-full h-screen">
          <Sidebar />
          <div className="border-x-2 border-black w-full h-full col-span-9 overflow-y-scroll">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
